name: Check style

on:
  pull_request:
    branches: [ master ]

jobs:
  check_style:
    name: Scalafmt check style
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Check style
      run: sbt scalafmtSbtCheck scalafmtCheckAll
